name: Push Snowflake Docker Image

on:
  pull_request:
  create:
    tags:
      - v*

jobs:
  push-github:
    name: Push to GHCR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugins
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Push Snowflake Image to GitHub Registry
        uses: whoan/docker-build-with-cache-action@v5
        with:
          # https://docs.github.com/en/packages/learn-github-packages/publishing-a-package
          username: "${{ secrets.FLYTE_BOT_USERNAME }}"
          password: "${{ secrets.FLYTE_BOT_PAT }}"
          image_name: ${{ github.repository_owner }}/flytekit
          image_tag: snowflake-${{ github.sha }},snowflake-${{ github.event.ref }}
          push_git_tag: ${{ github.event_name != 'pull_request' }}
          push_image_and_stages: ${{ github.event_name != 'pull_request' }}
          registry: ghcr.io
          build_extra_args: "--compress=true --build-arg=tag=ghcr.io/${{ github.repository_owner }}/flytekit:snowflake-${{ github.sha }}"
          context: "./plugins/flytekit-snowflake/flytekitplugins/"
          dockerfile: snowflake/Dockerfile